[project]
name = "surmeier-lab-to-nwb"
version = "0.0.1"
description = "NWB conversion scripts, functions, and classes for Surmeier  conversion"
readme = "README.md"
authors = [{ name = "CatalystNeuro", email = "ben.dichter@catalystneuro.com" }]
maintainers = [{ name = "CatalystNeuro", email = "ben.dichter@catalystneuro.com" }]
license = { file = "LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
  "neuroconv>=0.7.4",
  "nwbinspector",
  "lxml",
  "nd2>=0.10.3",
  "xmltodict>=0.14.2",
  "tifffile>=2025.5.10",
  "roiextractors>=0.5.13",
  "hdmf==4.0.0",
  "astropy>=6.1.7",
]

[project.urls]
Repository="https://github.com/catalystneuro/surmeier-lab-to-nwb"

[project.optional-dependencies]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
  "*.yaml",
  "*.yml",
  "*.json",
]  # This includes the yaml (usually metadata) and any schemas you might need on both the sdist and wheel

[tool.hatch.build.targets.wheel]
packages = ["src/surmeier_lab_to_nwb"]

[tool.hatch.build.targets.sdist]
packages = ["src/surmeier_lab_to_nwb"]

[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.toml
  |\.yml
  |\.md
  |\.txt
  |\.sh
  |\.git
  |\.ini
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''


[tool.codespell]
skip = '*.git*,*.pdf,*.css, *.ipynb'
check-hidden = true
ignore-words-list = 'assertin'


[tool.ruff]

[tool.ruff.lint]
select = [
    "F401",  # Unused import
    "I",  # All isort rules
]
fixable = ["ALL"]

[tool.ruff.lint.isort]
relative-imports-order = "closest-to-furthest"
known-first-party = ["surmeier_lab_to_nwb"]

[tool.uv.sources]
neuroconv = { path = "../neuroconv", editable = true }
roiextractors = { path = "../roiextractors", editable = true }

[tool.uv]
config-settings = { editable_mode = "compat" }

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "pre-commit>=4.2.0",
]
